# Generated by Django 5.1.7 on 2025-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, max_length=2000, null=True)),
                ('Demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('Source_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('Created', models.TimeField(auto_now_add=True)),
                ('ID', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
