# Generated by Django 5.1.7 on 2025-04-15 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Vote_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_ratio',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('Body', models.TextField(blank=True, max_length=2000, null=True)),
                ('Value', models.IntegerField(choices=[('up', 'up vote'), ('down', 'down vote')])),
                ('Created', models.TimeField(auto_now_add=True)),
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Tags',
            field=models.ManyToManyField(to='projects.tag'),
        ),
    ]
