# Generated by Django 5.1.7 on 2025-04-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_project_vote_total_project_vote_ratio_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Value',
            field=models.CharField(choices=[('up', 'up vote'), ('down', 'down vote')], max_length=50),
        ),
    ]
