# Generated by Django 5.2 on 2025-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_featured_image_alter_project_vote_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ID',
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
